name: Deploy React App to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.15.0

    - name: Install Dependencies
      run: npm ci

    - name: Build React App for Production
      run: npm run build

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: react-app-dev:${{ env.GITHUB_SHA }}
        context: .

    - name: Deploy to EC2
      uses: aws-actions/ec2-instance-management@v2
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
        instance_ids: i-0f93db0dfa1468ef1
        command: start
        tags: Name=react-dev
        user-data: |
          #!/bin/bash
          sudo docker run -d -p 80:80 react-app-dev:${{ env.GITHUB_SHA }}
