name: Deploy React App to EC2

on:
  push:
    branches: [ "deployment-testing" ]
  pull_request:
    branches: [ "deployment-testing" ]
env:
  AWS_REGION: us-east-2
  DOCKER_TAG: 0.1
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
    
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Log Secret
      run: echo "${{ secrets.TEST_SECRET_1 }}"

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present


#     - name: Login to Docker registry
#       run: |
#         echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY --username "$DOCKER_USERNAME" --password-stdin


#     - name: Build Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: true
#         tags: ${{ env.DOCKER_TAG }}

#     - name: Deploy to EC2
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         region: us-east-2
#         instance_ids: i-0f93db0dfa1468ef1
#         command: start
#         tags: Name=react-app
#         user-data: |
#           #!/bin/bash
#           sudo docker run -d -p 80:80 "image-${{ env.GITHUB_SHA }}"
