name: Deploy React App to EC2

on:
  push:
    branches: [ "deployment-testing" ]
  pull_request:
    branches: [ "deployment-testing" ]
env:
  AWS_REGION: us-east-2
  DOCKER_TAG: 0.1
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
   
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log Secret
      run: echo "${{ vars.AWS_INSTANCE_USER }}"

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
         
#     - name: Build and push
#       uses: docker/build-push-action@v4
#       with:
#           push: true
#           tags: iampsjain/react-complete-guide:latest

    - name: Configure SSH
      run: |
          echo " ${{ secrets.ECS_SSHKEY }}" | tr -d '\r' > ~/login.txt
          chmod 400 ~/login.txt 

    - name: Log in to Docker and pull the latest image
      run: |
          ssh -o StrictHostKeyChecking=no -i ~/login.txt ec2-user@${{ vars.AWS_HOST_NAME }} \
          "docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && \
          docker pull ${{ vars.DOCKER_IMAGE}} && \
          docker run ${{ vars.DOCKER_IMAGE}}"
